language: php
script: composer dump-autoload && phpunit --bootstrap vendor/autoload.php tests/VehicleClientTest.php
php:
  - '7.0'
  - hhvm
  - nightly
addons:
    code_climate:
        repo_token: fc6c9e3297a414ac544133b02c8ee15958a1f95bbe93df275cd09bc3125e4f5c